//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaAdmin.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CinemaAdmin.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхід в систему.
        /// </summary>
        public static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запам&apos;ятати мене.
        /// </summary>
        public static string CheckBoxRememberMe {
            get {
                return ResourceManager.GetString("CheckBoxRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва фільму.
        /// </summary>
        public static string DataGridColumnFilm {
            get {
                return ResourceManager.GetString("DataGridColumnFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва зали.
        /// </summary>
        public static string DataGridColumnHall {
            get {
                return ResourceManager.GetString("DataGridColumnHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продано.
        /// </summary>
        public static string DataGridColumnIsPaid {
            get {
                return ResourceManager.GetString("DataGridColumnIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заброньовано.
        /// </summary>
        public static string DataGridColumnIsToBook {
            get {
                return ResourceManager.GetString("DataGridColumnIsToBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість.
        /// </summary>
        public static string DataGridColumnPrice {
            get {
                return ResourceManager.GetString("DataGridColumnPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ряд.
        /// </summary>
        public static string DataGridColumnRow {
            get {
                return ResourceManager.GetString("DataGridColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Місце.
        /// </summary>
        public static string DataGridColumnSeat {
            get {
                return ResourceManager.GetString("DataGridColumnSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День сеансу.
        /// </summary>
        public static string DataGridColumnSessionData {
            get {
                return ResourceManager.GetString("DataGridColumnSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Час сеансу.
        /// </summary>
        public static string DataGridColumnSessionTime {
            get {
                return ResourceManager.GetString("DataGridColumnSessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не вдалося підключитися до бази даних. Зверніться до Адміністратора для вирішення даної проблеми..
        /// </summary>
        public static string ErrorCheckConnectionDB {
            get {
                return ResourceManager.GetString("ErrorCheckConnectionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхід в систему.
        /// </summary>
        public static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, авторизуйтеся....
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відсутнє підключення до бази....
        /// </summary>
        public static string LabelConnection {
            get {
                return ResourceManager.GetString("LabelConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторити спробу підключення до бази. При відсутності даного поля, підключення присутнє..
        /// </summary>
        public static string LabelConnectionToolTip {
            get {
                return ResourceManager.GetString("LabelConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string LabelDateTime {
            get {
                return ResourceManager.GetString("LabelDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва фільму:.
        /// </summary>
        public static string LabelFilmName {
            get {
                return ResourceManager.GetString("LabelFilmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошук....
        /// </summary>
        public static string LabelFind {
            get {
                return ResourceManager.GetString("LabelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва зали:.
        /// </summary>
        public static string LabelHallName {
            get {
                return ResourceManager.GetString("LabelHallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Залишок квитків:.
        /// </summary>
        public static string LabelLastTickets {
            get {
                return ResourceManager.GetString("LabelLastTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін.
        /// </summary>
        public static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продано квитків:.
        /// </summary>
        public static string LabelSellTickets {
            get {
                return ResourceManager.GetString("LabelSellTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розклад сеансів:.
        /// </summary>
        public static string LabelSession {
            get {
                return ResourceManager.GetString("LabelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квитки на сеанс:.
        /// </summary>
        public static string LabelTicket {
            get {
                return ResourceManager.GetString("LabelTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заброньовано квитків:.
        /// </summary>
        public static string LabelToBookTickets {
            get {
                return ResourceManager.GetString("LabelToBookTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити користувача....
        /// </summary>
        public static string MenuChangeUser {
            get {
                return ResourceManager.GetString("MenuChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихід.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Програма.
        /// </summary>
        public static string MenuItem1 {
            get {
                return ResourceManager.GetString("MenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оновити сеанси.
        /// </summary>
        public static string MenuItemRefresh {
            get {
                return ResourceManager.GetString("MenuItemRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відсутнє підключення до бази. Повторіть спробу пізніше. .
        /// </summary>
        public static string SignInConnection {
            get {
                return ResourceManager.GetString("SignInConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виникли проблеми в пошуку акаунта. Зверніться до Адміністратора для вирішення даної проблеми..
        /// </summary>
        public static string SignInForbidden {
            get {
                return ResourceManager.GetString("SignInForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш акаунт немає прав адміністратора. Зверніться до Адміністратора для вирішення даної проблеми..
        /// </summary>
        public static string SignInNotAdmin {
            get {
                return ResourceManager.GetString("SignInNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін або пароль введено невірно! Перевірте коректність введених даних та повторіть спробу іще раз..
        /// </summary>
        public static string SignInNotFound {
            get {
                return ResourceManager.GetString("SignInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизація виконана успішно!
        ///Ви ввійшли як.
        /// </summary>
        public static string SignInSuccessful {
            get {
                return ResourceManager.GetString("SignInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш акаунт неактивний. Зверніться до Адміністратора для активації..
        /// </summary>
        public static string SignInUnauthorized {
            get {
                return ResourceManager.GetString("SignInUnauthorized", resourceCulture);
            }
        }
    }
}
