//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinema.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхід в систему.
        /// </summary>
        public static string bttnSignIn {
            get {
                return ResourceManager.GetString("bttnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запам&apos;ятати мене.
        /// </summary>
        public static string checkRememberMe {
            get {
                return ResourceManager.GetString("checkRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не вдалося підключитися до бази даних. Зверніться до Адміністратора для вирішення даної проблеми..
        /// </summary>
        public static string ErrorCheckConnectionDB {
            get {
                return ResourceManager.GetString("ErrorCheckConnectionDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхід в систему.
        /// </summary>
        public static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, авторизуйтеся....
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відсутнє підключення до бази....
        /// </summary>
        public static string lConnection {
            get {
                return ResourceManager.GetString("lConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторити спробу підключення до бази. При відсутності даного поля, підключення присутнє..
        /// </summary>
        public static string lConnectionToolTip {
            get {
                return ResourceManager.GetString("lConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін.
        /// </summary>
        public static string lLogin {
            get {
                return ResourceManager.GetString("lLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string lPassword {
            get {
                return ResourceManager.GetString("lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відсутнє підключення до бази. Повторіть спробу пізніше. .
        /// </summary>
        public static string SignInConnection {
            get {
                return ResourceManager.GetString("SignInConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виникли проблеми в пошуку акаунта. Зверніться до Адміністратора для вирішення даної проблеми..
        /// </summary>
        public static string SignInForbidden {
            get {
                return ResourceManager.GetString("SignInForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін або пароль введено невірно! Перевірте коректність введених даних та повторіть спробу іще раз..
        /// </summary>
        public static string SignInNotFound {
            get {
                return ResourceManager.GetString("SignInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизація виконана успішно!
        ///Ви ввійшли як.
        /// </summary>
        public static string SignInSuccessful {
            get {
                return ResourceManager.GetString("SignInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш акаунт неактивний. Зверніться до Адміністратора для активації..
        /// </summary>
        public static string SignInUnauthorized {
            get {
                return ResourceManager.GetString("SignInUnauthorized", resourceCulture);
            }
        }
    }
}
